// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/eventos_transacao.proto

package br.com.pine.gerenciador.modelo.dominio.transacao.eventos;

public interface CategoriasAtualizadasOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transacao.eventos.CategoriasAtualizadas)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string categorias = 1;</code>
   * @return A list containing the categorias.
   */
  java.util.List<java.lang.String>
      getCategoriasList();
  /**
   * <code>repeated string categorias = 1;</code>
   * @return The count of categorias.
   */
  int getCategoriasCount();
  /**
   * <code>repeated string categorias = 1;</code>
   * @param index The index of the element to return.
   * @return The categorias at the given index.
   */
  java.lang.String getCategorias(int index);
  /**
   * <code>repeated string categorias = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the categorias at the given index.
   */
  com.google.protobuf.ByteString
      getCategoriasBytes(int index);
}
