// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/eventos_transacao.proto

package br.com.pine.gerenciador.modelo.dominio.transacao.eventos;

public final class EventosTransacao {
  private EventosTransacao() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transacao_eventos_TransacaoCriada_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transacao_eventos_TransacaoCriada_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transacao_eventos_ItemAdicionado_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transacao_eventos_ItemAdicionado_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transacao_eventos_ItemAlterado_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transacao_eventos_ItemAlterado_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transacao_eventos_ItemRemovido_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transacao_eventos_ItemRemovido_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transacao_eventos_CategoriasAtualizadas_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transacao_eventos_CategoriasAtualizadas_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transacao_eventos_EventoTransacao_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transacao_eventos_EventoTransacao_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transacao_eventos_ObjetosDeValor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transacao_eventos_ObjetosDeValor_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transacao_eventos_ObjetosDeValor_ValorItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transacao_eventos_ObjetosDeValor_ValorItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transacao_eventos_ObjetosDeValor_Quantidade_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transacao_eventos_ObjetosDeValor_Quantidade_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transacao_eventos_ObjetosDeValor_ValorMonetario_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transacao_eventos_ObjetosDeValor_ValorMonetario_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035proto/eventos_transacao.proto\022\021transac" +
      "ao.eventos\"c\n\017TransacaoCriada\022\017\n\002id\030\001 \001(" +
      "\tH\000\210\001\001\022\026\n\tpagamento\030\002 \001(\tH\001\210\001\001\022\022\n\ncatego" +
      "rias\030\003 \003(\tB\005\n\003_idB\014\n\n_pagamento\"\237\001\n\016Item" +
      "Adicionado\022\026\n\tdescricao\030\001 \001(\tH\000\210\001\001\022D\n\nva" +
      "lor_item\030\002 \001(\0132+.transacao.eventos.Objet" +
      "osDeValor.ValorItemH\001\210\001\001\022\022\n\ncategorias\030\003" +
      " \003(\tB\014\n\n_descricaoB\r\n\013_valor_item\"\351\001\n\014It" +
      "emAlterado\022\037\n\022descricao_original\030\001 \001(\tH\000" +
      "\210\001\001\022\033\n\016descricao_nova\030\002 \001(\tH\001\210\001\001\022I\n\017valo" +
      "r_item_novo\030\003 \001(\0132+.transacao.eventos.Ob" +
      "jetosDeValor.ValorItemH\002\210\001\001\022\022\n\ncategoria" +
      "s\030\004 \003(\tB\025\n\023_descricao_originalB\021\n\017_descr" +
      "icao_novaB\022\n\020_valor_item_novo\"4\n\014ItemRem" +
      "ovido\022\026\n\tdescricao\030\001 \001(\tH\000\210\001\001B\014\n\n_descri" +
      "cao\"+\n\025CategoriasAtualizadas\022\022\n\ncategori" +
      "as\030\001 \003(\t\"\322\003\n\017EventoTransacao\022\030\n\013ocorrido" +
      "_em\030\001 \001(\tH\001\210\001\001\022\032\n\rversao_evento\030\002 \001(\005H\002\210" +
      "\001\001\022\021\n\004tipo\030\003 \001(\tH\003\210\001\001\022>\n\020transacao_criad" +
      "a\030\004 \001(\0132\".transacao.eventos.TransacaoCri" +
      "adaH\000\022<\n\017item_adicionado\030\005 \001(\0132!.transac" +
      "ao.eventos.ItemAdicionadoH\000\0228\n\ritem_alte" +
      "rado\030\006 \001(\0132\037.transacao.eventos.ItemAlter" +
      "adoH\000\0228\n\ritem_removido\030\007 \001(\0132\037.transacao" +
      ".eventos.ItemRemovidoH\000\022J\n\026categorias_at" +
      "ualizadas\030\010 \001(\0132(.transacao.eventos.Cate" +
      "goriasAtualizadasH\000B\r\n\013tipo_eventoB\016\n\014_o" +
      "corrido_emB\020\n\016_versao_eventoB\007\n\005_tipo\"\230\003" +
      "\n\016ObjetosDeValor\032\301\001\n\tValorItem\022E\n\nquanti" +
      "dade\030\001 \001(\0132,.transacao.eventos.ObjetosDe" +
      "Valor.QuantidadeH\000\210\001\001\022L\n\rvalorUnitario\030\002" +
      " \001(\01320.transacao.eventos.ObjetosDeValor." +
      "ValorMonetarioH\001\210\001\001B\r\n\013_quantidadeB\020\n\016_v" +
      "alorUnitario\032t\n\nQuantidade\022\032\n\rmultiplica" +
      "dor\030\001 \001(\002H\000\210\001\001\022 \n\023tipo_unidade_medida\030\002 " +
      "\001(\tH\001\210\001\001B\020\n\016_multiplicadorB\026\n\024_tipo_unid" +
      "ade_medida\032L\n\016ValorMonetario\022\022\n\005moeda\030\001 " +
      "\001(\tH\000\210\001\001\022\022\n\005valor\030\002 \001(\002H\001\210\001\001B\010\n\006_moedaB\010" +
      "\n\006_valorBN\n8br.com.pine.gerenciador.mode" +
      "lo.dominio.transacao.eventosB\020EventosTra" +
      "nsacaoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_transacao_eventos_TransacaoCriada_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_transacao_eventos_TransacaoCriada_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transacao_eventos_TransacaoCriada_descriptor,
        new java.lang.String[] { "Id", "Pagamento", "Categorias", "Id", "Pagamento", });
    internal_static_transacao_eventos_ItemAdicionado_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_transacao_eventos_ItemAdicionado_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transacao_eventos_ItemAdicionado_descriptor,
        new java.lang.String[] { "Descricao", "ValorItem", "Categorias", "Descricao", "ValorItem", });
    internal_static_transacao_eventos_ItemAlterado_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_transacao_eventos_ItemAlterado_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transacao_eventos_ItemAlterado_descriptor,
        new java.lang.String[] { "DescricaoOriginal", "DescricaoNova", "ValorItemNovo", "Categorias", "DescricaoOriginal", "DescricaoNova", "ValorItemNovo", });
    internal_static_transacao_eventos_ItemRemovido_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_transacao_eventos_ItemRemovido_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transacao_eventos_ItemRemovido_descriptor,
        new java.lang.String[] { "Descricao", "Descricao", });
    internal_static_transacao_eventos_CategoriasAtualizadas_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_transacao_eventos_CategoriasAtualizadas_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transacao_eventos_CategoriasAtualizadas_descriptor,
        new java.lang.String[] { "Categorias", });
    internal_static_transacao_eventos_EventoTransacao_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_transacao_eventos_EventoTransacao_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transacao_eventos_EventoTransacao_descriptor,
        new java.lang.String[] { "OcorridoEm", "VersaoEvento", "Tipo", "TransacaoCriada", "ItemAdicionado", "ItemAlterado", "ItemRemovido", "CategoriasAtualizadas", "TipoEvento", "OcorridoEm", "VersaoEvento", "Tipo", });
    internal_static_transacao_eventos_ObjetosDeValor_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_transacao_eventos_ObjetosDeValor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transacao_eventos_ObjetosDeValor_descriptor,
        new java.lang.String[] { });
    internal_static_transacao_eventos_ObjetosDeValor_ValorItem_descriptor =
      internal_static_transacao_eventos_ObjetosDeValor_descriptor.getNestedTypes().get(0);
    internal_static_transacao_eventos_ObjetosDeValor_ValorItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transacao_eventos_ObjetosDeValor_ValorItem_descriptor,
        new java.lang.String[] { "Quantidade", "ValorUnitario", "Quantidade", "ValorUnitario", });
    internal_static_transacao_eventos_ObjetosDeValor_Quantidade_descriptor =
      internal_static_transacao_eventos_ObjetosDeValor_descriptor.getNestedTypes().get(1);
    internal_static_transacao_eventos_ObjetosDeValor_Quantidade_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transacao_eventos_ObjetosDeValor_Quantidade_descriptor,
        new java.lang.String[] { "Multiplicador", "TipoUnidadeMedida", "Multiplicador", "TipoUnidadeMedida", });
    internal_static_transacao_eventos_ObjetosDeValor_ValorMonetario_descriptor =
      internal_static_transacao_eventos_ObjetosDeValor_descriptor.getNestedTypes().get(2);
    internal_static_transacao_eventos_ObjetosDeValor_ValorMonetario_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transacao_eventos_ObjetosDeValor_ValorMonetario_descriptor,
        new java.lang.String[] { "Moeda", "Valor", "Moeda", "Valor", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
