// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventos_transacao.proto

package br.com.pine.gerenciador.modelo.dominio.transacao.eventos;

public final class EventosTransacao {
  private EventosTransacao() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transacao_eventos_TransacaoCriada_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transacao_eventos_TransacaoCriada_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transacao_eventos_ItemAdicionado_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transacao_eventos_ItemAdicionado_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transacao_eventos_ItemAlterado_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transacao_eventos_ItemAlterado_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transacao_eventos_ItemRemovido_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transacao_eventos_ItemRemovido_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transacao_eventos_CategoriasAtualizadas_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transacao_eventos_CategoriasAtualizadas_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transacao_eventos_EventoTransacao_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transacao_eventos_EventoTransacao_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transacao_eventos_ObjetosDeValor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transacao_eventos_ObjetosDeValor_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transacao_eventos_ObjetosDeValor_ValorItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transacao_eventos_ObjetosDeValor_ValorItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transacao_eventos_ObjetosDeValor_Quantidade_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transacao_eventos_ObjetosDeValor_Quantidade_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transacao_eventos_ObjetosDeValor_ValorMonetario_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transacao_eventos_ObjetosDeValor_ValorMonetario_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027eventos_transacao.proto\022\021transacao.eve" +
      "ntos\"c\n\017TransacaoCriada\022\017\n\002id\030\001 \001(\tH\000\210\001\001" +
      "\022\026\n\tpagamento\030\002 \001(\tH\001\210\001\001\022\022\n\ncategorias\030\003" +
      " \003(\tB\005\n\003_idB\014\n\n_pagamento\"\237\001\n\016ItemAdicio" +
      "nado\022\026\n\tdescricao\030\001 \001(\tH\000\210\001\001\022D\n\nvalor_it" +
      "em\030\002 \001(\0132+.transacao.eventos.ObjetosDeVa" +
      "lor.ValorItemH\001\210\001\001\022\022\n\ncategorias\030\003 \003(\tB\014" +
      "\n\n_descricaoB\r\n\013_valor_item\"\351\001\n\014ItemAlte" +
      "rado\022\037\n\022descricao_original\030\001 \001(\tH\000\210\001\001\022\033\n" +
      "\016descricao_nova\030\002 \001(\tH\001\210\001\001\022I\n\017valor_item" +
      "_novo\030\003 \001(\0132+.transacao.eventos.ObjetosD" +
      "eValor.ValorItemH\002\210\001\001\022\022\n\ncategorias\030\004 \003(" +
      "\tB\025\n\023_descricao_originalB\021\n\017_descricao_n" +
      "ovaB\022\n\020_valor_item_novo\"4\n\014ItemRemovido\022" +
      "\026\n\tdescricao\030\001 \001(\tH\000\210\001\001B\014\n\n_descricao\"+\n" +
      "\025CategoriasAtualizadas\022\022\n\ncategorias\030\001 \003" +
      "(\t\"\322\003\n\017EventoTransacao\022\030\n\013ocorrido_em\030\001 " +
      "\001(\tH\001\210\001\001\022\032\n\rversao_evento\030\002 \001(\005H\002\210\001\001\022\021\n\004" +
      "tipo\030\003 \001(\tH\003\210\001\001\022>\n\020transacao_criada\030\004 \001(" +
      "\0132\".transacao.eventos.TransacaoCriadaH\000\022" +
      "<\n\017item_adicionado\030\005 \001(\0132!.transacao.eve" +
      "ntos.ItemAdicionadoH\000\0228\n\ritem_alterado\030\006" +
      " \001(\0132\037.transacao.eventos.ItemAlteradoH\000\022" +
      "8\n\ritem_removido\030\007 \001(\0132\037.transacao.event" +
      "os.ItemRemovidoH\000\022J\n\026categorias_atualiza" +
      "das\030\010 \001(\0132(.transacao.eventos.Categorias" +
      "AtualizadasH\000B\r\n\013tipo_eventoB\016\n\014_ocorrid" +
      "o_emB\020\n\016_versao_eventoB\007\n\005_tipo\"\230\003\n\016Obje" +
      "tosDeValor\032\301\001\n\tValorItem\022E\n\nquantidade\030\001" +
      " \001(\0132,.transacao.eventos.ObjetosDeValor." +
      "QuantidadeH\000\210\001\001\022L\n\rvalorUnitario\030\002 \001(\01320" +
      ".transacao.eventos.ObjetosDeValor.ValorM" +
      "onetarioH\001\210\001\001B\r\n\013_quantidadeB\020\n\016_valorUn" +
      "itario\032t\n\nQuantidade\022\032\n\rmultiplicador\030\001 " +
      "\001(\002H\000\210\001\001\022 \n\023tipo_unidade_medida\030\002 \001(\tH\001\210" +
      "\001\001B\020\n\016_multiplicadorB\026\n\024_tipo_unidade_me" +
      "dida\032L\n\016ValorMonetario\022\022\n\005moeda\030\001 \001(\tH\000\210" +
      "\001\001\022\022\n\005valor\030\002 \001(\002H\001\210\001\001B\010\n\006_moedaB\010\n\006_val" +
      "orBN\n8br.com.pine.gerenciador.modelo.dom" +
      "inio.transacao.eventosB\020EventosTransacao" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_transacao_eventos_TransacaoCriada_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_transacao_eventos_TransacaoCriada_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transacao_eventos_TransacaoCriada_descriptor,
        new java.lang.String[] { "Id", "Pagamento", "Categorias", "Id", "Pagamento", });
    internal_static_transacao_eventos_ItemAdicionado_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_transacao_eventos_ItemAdicionado_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transacao_eventos_ItemAdicionado_descriptor,
        new java.lang.String[] { "Descricao", "ValorItem", "Categorias", "Descricao", "ValorItem", });
    internal_static_transacao_eventos_ItemAlterado_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_transacao_eventos_ItemAlterado_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transacao_eventos_ItemAlterado_descriptor,
        new java.lang.String[] { "DescricaoOriginal", "DescricaoNova", "ValorItemNovo", "Categorias", "DescricaoOriginal", "DescricaoNova", "ValorItemNovo", });
    internal_static_transacao_eventos_ItemRemovido_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_transacao_eventos_ItemRemovido_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transacao_eventos_ItemRemovido_descriptor,
        new java.lang.String[] { "Descricao", "Descricao", });
    internal_static_transacao_eventos_CategoriasAtualizadas_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_transacao_eventos_CategoriasAtualizadas_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transacao_eventos_CategoriasAtualizadas_descriptor,
        new java.lang.String[] { "Categorias", });
    internal_static_transacao_eventos_EventoTransacao_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_transacao_eventos_EventoTransacao_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transacao_eventos_EventoTransacao_descriptor,
        new java.lang.String[] { "OcorridoEm", "VersaoEvento", "Tipo", "TransacaoCriada", "ItemAdicionado", "ItemAlterado", "ItemRemovido", "CategoriasAtualizadas", "TipoEvento", "OcorridoEm", "VersaoEvento", "Tipo", });
    internal_static_transacao_eventos_ObjetosDeValor_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_transacao_eventos_ObjetosDeValor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transacao_eventos_ObjetosDeValor_descriptor,
        new java.lang.String[] { });
    internal_static_transacao_eventos_ObjetosDeValor_ValorItem_descriptor =
      internal_static_transacao_eventos_ObjetosDeValor_descriptor.getNestedTypes().get(0);
    internal_static_transacao_eventos_ObjetosDeValor_ValorItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transacao_eventos_ObjetosDeValor_ValorItem_descriptor,
        new java.lang.String[] { "Quantidade", "ValorUnitario", "Quantidade", "ValorUnitario", });
    internal_static_transacao_eventos_ObjetosDeValor_Quantidade_descriptor =
      internal_static_transacao_eventos_ObjetosDeValor_descriptor.getNestedTypes().get(1);
    internal_static_transacao_eventos_ObjetosDeValor_Quantidade_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transacao_eventos_ObjetosDeValor_Quantidade_descriptor,
        new java.lang.String[] { "Multiplicador", "TipoUnidadeMedida", "Multiplicador", "TipoUnidadeMedida", });
    internal_static_transacao_eventos_ObjetosDeValor_ValorMonetario_descriptor =
      internal_static_transacao_eventos_ObjetosDeValor_descriptor.getNestedTypes().get(2);
    internal_static_transacao_eventos_ObjetosDeValor_ValorMonetario_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transacao_eventos_ObjetosDeValor_ValorMonetario_descriptor,
        new java.lang.String[] { "Moeda", "Valor", "Moeda", "Valor", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
