// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/eventos_transacao.proto

package br.com.pine.gerenciador.modelo.dominio.transacao.eventos;

public interface EventoTransacaoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transacao.eventos.EventoTransacao)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string ocorrido_em = 1;</code>
   * @return Whether the ocorridoEm field is set.
   */
  boolean hasOcorridoEm();
  /**
   * <code>optional string ocorrido_em = 1;</code>
   * @return The ocorridoEm.
   */
  java.lang.String getOcorridoEm();
  /**
   * <code>optional string ocorrido_em = 1;</code>
   * @return The bytes for ocorridoEm.
   */
  com.google.protobuf.ByteString
      getOcorridoEmBytes();

  /**
   * <code>optional int32 versao_evento = 2;</code>
   * @return Whether the versaoEvento field is set.
   */
  boolean hasVersaoEvento();
  /**
   * <code>optional int32 versao_evento = 2;</code>
   * @return The versaoEvento.
   */
  int getVersaoEvento();

  /**
   * <code>optional string tipo = 3;</code>
   * @return Whether the tipo field is set.
   */
  boolean hasTipo();
  /**
   * <code>optional string tipo = 3;</code>
   * @return The tipo.
   */
  java.lang.String getTipo();
  /**
   * <code>optional string tipo = 3;</code>
   * @return The bytes for tipo.
   */
  com.google.protobuf.ByteString
      getTipoBytes();

  /**
   * <code>.transacao.eventos.TransacaoCriada transacao_criada = 4;</code>
   * @return Whether the transacaoCriada field is set.
   */
  boolean hasTransacaoCriada();
  /**
   * <code>.transacao.eventos.TransacaoCriada transacao_criada = 4;</code>
   * @return The transacaoCriada.
   */
  br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada getTransacaoCriada();
  /**
   * <code>.transacao.eventos.TransacaoCriada transacao_criada = 4;</code>
   */
  br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriadaOrBuilder getTransacaoCriadaOrBuilder();

  /**
   * <code>.transacao.eventos.ItemAdicionado item_adicionado = 5;</code>
   * @return Whether the itemAdicionado field is set.
   */
  boolean hasItemAdicionado();
  /**
   * <code>.transacao.eventos.ItemAdicionado item_adicionado = 5;</code>
   * @return The itemAdicionado.
   */
  br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado getItemAdicionado();
  /**
   * <code>.transacao.eventos.ItemAdicionado item_adicionado = 5;</code>
   */
  br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionadoOrBuilder getItemAdicionadoOrBuilder();

  /**
   * <code>.transacao.eventos.ItemAlterado item_alterado = 6;</code>
   * @return Whether the itemAlterado field is set.
   */
  boolean hasItemAlterado();
  /**
   * <code>.transacao.eventos.ItemAlterado item_alterado = 6;</code>
   * @return The itemAlterado.
   */
  br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado getItemAlterado();
  /**
   * <code>.transacao.eventos.ItemAlterado item_alterado = 6;</code>
   */
  br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlteradoOrBuilder getItemAlteradoOrBuilder();

  /**
   * <code>.transacao.eventos.ItemRemovido item_removido = 7;</code>
   * @return Whether the itemRemovido field is set.
   */
  boolean hasItemRemovido();
  /**
   * <code>.transacao.eventos.ItemRemovido item_removido = 7;</code>
   * @return The itemRemovido.
   */
  br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido getItemRemovido();
  /**
   * <code>.transacao.eventos.ItemRemovido item_removido = 7;</code>
   */
  br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovidoOrBuilder getItemRemovidoOrBuilder();

  /**
   * <code>.transacao.eventos.CategoriasAtualizadas categorias_atualizadas = 8;</code>
   * @return Whether the categoriasAtualizadas field is set.
   */
  boolean hasCategoriasAtualizadas();
  /**
   * <code>.transacao.eventos.CategoriasAtualizadas categorias_atualizadas = 8;</code>
   * @return The categoriasAtualizadas.
   */
  br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas getCategoriasAtualizadas();
  /**
   * <code>.transacao.eventos.CategoriasAtualizadas categorias_atualizadas = 8;</code>
   */
  br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadasOrBuilder getCategoriasAtualizadasOrBuilder();

  public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao.TipoEventoCase getTipoEventoCase();
}
