// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/eventos_transacao.proto

package br.com.pine.gerenciador.modelo.dominio.transacao.eventos;

/**
 * Protobuf type {@code transacao.eventos.EventoTransacao}
 */
public final class EventoTransacao extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:transacao.eventos.EventoTransacao)
    EventoTransacaoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EventoTransacao.newBuilder() to construct.
  private EventoTransacao(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EventoTransacao() {
    ocorridoEm_ = "";
    tipo_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EventoTransacao();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventosTransacao.internal_static_transacao_eventos_EventoTransacao_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventosTransacao.internal_static_transacao_eventos_EventoTransacao_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao.class, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao.Builder.class);
  }

  private int bitField0_;
  private int tipoEventoCase_ = 0;
  private java.lang.Object tipoEvento_;
  public enum TipoEventoCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    TRANSACAO_CRIADA(4),
    ITEM_ADICIONADO(5),
    ITEM_ALTERADO(6),
    ITEM_REMOVIDO(7),
    CATEGORIAS_ATUALIZADAS(8),
    TIPOEVENTO_NOT_SET(0);
    private final int value;
    private TipoEventoCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TipoEventoCase valueOf(int value) {
      return forNumber(value);
    }

    public static TipoEventoCase forNumber(int value) {
      switch (value) {
        case 4: return TRANSACAO_CRIADA;
        case 5: return ITEM_ADICIONADO;
        case 6: return ITEM_ALTERADO;
        case 7: return ITEM_REMOVIDO;
        case 8: return CATEGORIAS_ATUALIZADAS;
        case 0: return TIPOEVENTO_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public TipoEventoCase
  getTipoEventoCase() {
    return TipoEventoCase.forNumber(
        tipoEventoCase_);
  }

  public static final int OCORRIDO_EM_FIELD_NUMBER = 1;
  private volatile java.lang.Object ocorridoEm_;
  /**
   * <code>optional string ocorrido_em = 1;</code>
   * @return Whether the ocorridoEm field is set.
   */
  @java.lang.Override
  public boolean hasOcorridoEm() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string ocorrido_em = 1;</code>
   * @return The ocorridoEm.
   */
  @java.lang.Override
  public java.lang.String getOcorridoEm() {
    java.lang.Object ref = ocorridoEm_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ocorridoEm_ = s;
      return s;
    }
  }
  /**
   * <code>optional string ocorrido_em = 1;</code>
   * @return The bytes for ocorridoEm.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOcorridoEmBytes() {
    java.lang.Object ref = ocorridoEm_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ocorridoEm_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSAO_EVENTO_FIELD_NUMBER = 2;
  private int versaoEvento_;
  /**
   * <code>optional int32 versao_evento = 2;</code>
   * @return Whether the versaoEvento field is set.
   */
  @java.lang.Override
  public boolean hasVersaoEvento() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int32 versao_evento = 2;</code>
   * @return The versaoEvento.
   */
  @java.lang.Override
  public int getVersaoEvento() {
    return versaoEvento_;
  }

  public static final int TIPO_FIELD_NUMBER = 3;
  private volatile java.lang.Object tipo_;
  /**
   * <code>optional string tipo = 3;</code>
   * @return Whether the tipo field is set.
   */
  @java.lang.Override
  public boolean hasTipo() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string tipo = 3;</code>
   * @return The tipo.
   */
  @java.lang.Override
  public java.lang.String getTipo() {
    java.lang.Object ref = tipo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tipo_ = s;
      return s;
    }
  }
  /**
   * <code>optional string tipo = 3;</code>
   * @return The bytes for tipo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTipoBytes() {
    java.lang.Object ref = tipo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tipo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSACAO_CRIADA_FIELD_NUMBER = 4;
  /**
   * <code>.transacao.eventos.TransacaoCriada transacao_criada = 4;</code>
   * @return Whether the transacaoCriada field is set.
   */
  @java.lang.Override
  public boolean hasTransacaoCriada() {
    return tipoEventoCase_ == 4;
  }
  /**
   * <code>.transacao.eventos.TransacaoCriada transacao_criada = 4;</code>
   * @return The transacaoCriada.
   */
  @java.lang.Override
  public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada getTransacaoCriada() {
    if (tipoEventoCase_ == 4) {
       return (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada) tipoEvento_;
    }
    return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada.getDefaultInstance();
  }
  /**
   * <code>.transacao.eventos.TransacaoCriada transacao_criada = 4;</code>
   */
  @java.lang.Override
  public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriadaOrBuilder getTransacaoCriadaOrBuilder() {
    if (tipoEventoCase_ == 4) {
       return (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada) tipoEvento_;
    }
    return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada.getDefaultInstance();
  }

  public static final int ITEM_ADICIONADO_FIELD_NUMBER = 5;
  /**
   * <code>.transacao.eventos.ItemAdicionado item_adicionado = 5;</code>
   * @return Whether the itemAdicionado field is set.
   */
  @java.lang.Override
  public boolean hasItemAdicionado() {
    return tipoEventoCase_ == 5;
  }
  /**
   * <code>.transacao.eventos.ItemAdicionado item_adicionado = 5;</code>
   * @return The itemAdicionado.
   */
  @java.lang.Override
  public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado getItemAdicionado() {
    if (tipoEventoCase_ == 5) {
       return (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado) tipoEvento_;
    }
    return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado.getDefaultInstance();
  }
  /**
   * <code>.transacao.eventos.ItemAdicionado item_adicionado = 5;</code>
   */
  @java.lang.Override
  public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionadoOrBuilder getItemAdicionadoOrBuilder() {
    if (tipoEventoCase_ == 5) {
       return (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado) tipoEvento_;
    }
    return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado.getDefaultInstance();
  }

  public static final int ITEM_ALTERADO_FIELD_NUMBER = 6;
  /**
   * <code>.transacao.eventos.ItemAlterado item_alterado = 6;</code>
   * @return Whether the itemAlterado field is set.
   */
  @java.lang.Override
  public boolean hasItemAlterado() {
    return tipoEventoCase_ == 6;
  }
  /**
   * <code>.transacao.eventos.ItemAlterado item_alterado = 6;</code>
   * @return The itemAlterado.
   */
  @java.lang.Override
  public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado getItemAlterado() {
    if (tipoEventoCase_ == 6) {
       return (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado) tipoEvento_;
    }
    return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado.getDefaultInstance();
  }
  /**
   * <code>.transacao.eventos.ItemAlterado item_alterado = 6;</code>
   */
  @java.lang.Override
  public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlteradoOrBuilder getItemAlteradoOrBuilder() {
    if (tipoEventoCase_ == 6) {
       return (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado) tipoEvento_;
    }
    return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado.getDefaultInstance();
  }

  public static final int ITEM_REMOVIDO_FIELD_NUMBER = 7;
  /**
   * <code>.transacao.eventos.ItemRemovido item_removido = 7;</code>
   * @return Whether the itemRemovido field is set.
   */
  @java.lang.Override
  public boolean hasItemRemovido() {
    return tipoEventoCase_ == 7;
  }
  /**
   * <code>.transacao.eventos.ItemRemovido item_removido = 7;</code>
   * @return The itemRemovido.
   */
  @java.lang.Override
  public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido getItemRemovido() {
    if (tipoEventoCase_ == 7) {
       return (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido) tipoEvento_;
    }
    return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido.getDefaultInstance();
  }
  /**
   * <code>.transacao.eventos.ItemRemovido item_removido = 7;</code>
   */
  @java.lang.Override
  public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovidoOrBuilder getItemRemovidoOrBuilder() {
    if (tipoEventoCase_ == 7) {
       return (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido) tipoEvento_;
    }
    return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido.getDefaultInstance();
  }

  public static final int CATEGORIAS_ATUALIZADAS_FIELD_NUMBER = 8;
  /**
   * <code>.transacao.eventos.CategoriasAtualizadas categorias_atualizadas = 8;</code>
   * @return Whether the categoriasAtualizadas field is set.
   */
  @java.lang.Override
  public boolean hasCategoriasAtualizadas() {
    return tipoEventoCase_ == 8;
  }
  /**
   * <code>.transacao.eventos.CategoriasAtualizadas categorias_atualizadas = 8;</code>
   * @return The categoriasAtualizadas.
   */
  @java.lang.Override
  public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas getCategoriasAtualizadas() {
    if (tipoEventoCase_ == 8) {
       return (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas) tipoEvento_;
    }
    return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas.getDefaultInstance();
  }
  /**
   * <code>.transacao.eventos.CategoriasAtualizadas categorias_atualizadas = 8;</code>
   */
  @java.lang.Override
  public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadasOrBuilder getCategoriasAtualizadasOrBuilder() {
    if (tipoEventoCase_ == 8) {
       return (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas) tipoEvento_;
    }
    return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ocorridoEm_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, versaoEvento_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, tipo_);
    }
    if (tipoEventoCase_ == 4) {
      output.writeMessage(4, (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada) tipoEvento_);
    }
    if (tipoEventoCase_ == 5) {
      output.writeMessage(5, (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado) tipoEvento_);
    }
    if (tipoEventoCase_ == 6) {
      output.writeMessage(6, (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado) tipoEvento_);
    }
    if (tipoEventoCase_ == 7) {
      output.writeMessage(7, (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido) tipoEvento_);
    }
    if (tipoEventoCase_ == 8) {
      output.writeMessage(8, (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas) tipoEvento_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ocorridoEm_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, versaoEvento_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, tipo_);
    }
    if (tipoEventoCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada) tipoEvento_);
    }
    if (tipoEventoCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado) tipoEvento_);
    }
    if (tipoEventoCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado) tipoEvento_);
    }
    if (tipoEventoCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido) tipoEvento_);
    }
    if (tipoEventoCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas) tipoEvento_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao)) {
      return super.equals(obj);
    }
    br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao other = (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao) obj;

    if (hasOcorridoEm() != other.hasOcorridoEm()) return false;
    if (hasOcorridoEm()) {
      if (!getOcorridoEm()
          .equals(other.getOcorridoEm())) return false;
    }
    if (hasVersaoEvento() != other.hasVersaoEvento()) return false;
    if (hasVersaoEvento()) {
      if (getVersaoEvento()
          != other.getVersaoEvento()) return false;
    }
    if (hasTipo() != other.hasTipo()) return false;
    if (hasTipo()) {
      if (!getTipo()
          .equals(other.getTipo())) return false;
    }
    if (!getTipoEventoCase().equals(other.getTipoEventoCase())) return false;
    switch (tipoEventoCase_) {
      case 4:
        if (!getTransacaoCriada()
            .equals(other.getTransacaoCriada())) return false;
        break;
      case 5:
        if (!getItemAdicionado()
            .equals(other.getItemAdicionado())) return false;
        break;
      case 6:
        if (!getItemAlterado()
            .equals(other.getItemAlterado())) return false;
        break;
      case 7:
        if (!getItemRemovido()
            .equals(other.getItemRemovido())) return false;
        break;
      case 8:
        if (!getCategoriasAtualizadas()
            .equals(other.getCategoriasAtualizadas())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasOcorridoEm()) {
      hash = (37 * hash) + OCORRIDO_EM_FIELD_NUMBER;
      hash = (53 * hash) + getOcorridoEm().hashCode();
    }
    if (hasVersaoEvento()) {
      hash = (37 * hash) + VERSAO_EVENTO_FIELD_NUMBER;
      hash = (53 * hash) + getVersaoEvento();
    }
    if (hasTipo()) {
      hash = (37 * hash) + TIPO_FIELD_NUMBER;
      hash = (53 * hash) + getTipo().hashCode();
    }
    switch (tipoEventoCase_) {
      case 4:
        hash = (37 * hash) + TRANSACAO_CRIADA_FIELD_NUMBER;
        hash = (53 * hash) + getTransacaoCriada().hashCode();
        break;
      case 5:
        hash = (37 * hash) + ITEM_ADICIONADO_FIELD_NUMBER;
        hash = (53 * hash) + getItemAdicionado().hashCode();
        break;
      case 6:
        hash = (37 * hash) + ITEM_ALTERADO_FIELD_NUMBER;
        hash = (53 * hash) + getItemAlterado().hashCode();
        break;
      case 7:
        hash = (37 * hash) + ITEM_REMOVIDO_FIELD_NUMBER;
        hash = (53 * hash) + getItemRemovido().hashCode();
        break;
      case 8:
        hash = (37 * hash) + CATEGORIAS_ATUALIZADAS_FIELD_NUMBER;
        hash = (53 * hash) + getCategoriasAtualizadas().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code transacao.eventos.EventoTransacao}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:transacao.eventos.EventoTransacao)
      br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacaoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventosTransacao.internal_static_transacao_eventos_EventoTransacao_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventosTransacao.internal_static_transacao_eventos_EventoTransacao_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao.class, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao.Builder.class);
    }

    // Construct using br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ocorridoEm_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      versaoEvento_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      tipo_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      if (transacaoCriadaBuilder_ != null) {
        transacaoCriadaBuilder_.clear();
      }
      if (itemAdicionadoBuilder_ != null) {
        itemAdicionadoBuilder_.clear();
      }
      if (itemAlteradoBuilder_ != null) {
        itemAlteradoBuilder_.clear();
      }
      if (itemRemovidoBuilder_ != null) {
        itemRemovidoBuilder_.clear();
      }
      if (categoriasAtualizadasBuilder_ != null) {
        categoriasAtualizadasBuilder_.clear();
      }
      tipoEventoCase_ = 0;
      tipoEvento_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventosTransacao.internal_static_transacao_eventos_EventoTransacao_descriptor;
    }

    @java.lang.Override
    public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao getDefaultInstanceForType() {
      return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao.getDefaultInstance();
    }

    @java.lang.Override
    public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao build() {
      br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao buildPartial() {
      br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao result = new br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.ocorridoEm_ = ocorridoEm_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.versaoEvento_ = versaoEvento_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.tipo_ = tipo_;
      if (tipoEventoCase_ == 4) {
        if (transacaoCriadaBuilder_ == null) {
          result.tipoEvento_ = tipoEvento_;
        } else {
          result.tipoEvento_ = transacaoCriadaBuilder_.build();
        }
      }
      if (tipoEventoCase_ == 5) {
        if (itemAdicionadoBuilder_ == null) {
          result.tipoEvento_ = tipoEvento_;
        } else {
          result.tipoEvento_ = itemAdicionadoBuilder_.build();
        }
      }
      if (tipoEventoCase_ == 6) {
        if (itemAlteradoBuilder_ == null) {
          result.tipoEvento_ = tipoEvento_;
        } else {
          result.tipoEvento_ = itemAlteradoBuilder_.build();
        }
      }
      if (tipoEventoCase_ == 7) {
        if (itemRemovidoBuilder_ == null) {
          result.tipoEvento_ = tipoEvento_;
        } else {
          result.tipoEvento_ = itemRemovidoBuilder_.build();
        }
      }
      if (tipoEventoCase_ == 8) {
        if (categoriasAtualizadasBuilder_ == null) {
          result.tipoEvento_ = tipoEvento_;
        } else {
          result.tipoEvento_ = categoriasAtualizadasBuilder_.build();
        }
      }
      result.bitField0_ = to_bitField0_;
      result.tipoEventoCase_ = tipoEventoCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao) {
        return mergeFrom((br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao other) {
      if (other == br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao.getDefaultInstance()) return this;
      if (other.hasOcorridoEm()) {
        bitField0_ |= 0x00000001;
        ocorridoEm_ = other.ocorridoEm_;
        onChanged();
      }
      if (other.hasVersaoEvento()) {
        setVersaoEvento(other.getVersaoEvento());
      }
      if (other.hasTipo()) {
        bitField0_ |= 0x00000004;
        tipo_ = other.tipo_;
        onChanged();
      }
      switch (other.getTipoEventoCase()) {
        case TRANSACAO_CRIADA: {
          mergeTransacaoCriada(other.getTransacaoCriada());
          break;
        }
        case ITEM_ADICIONADO: {
          mergeItemAdicionado(other.getItemAdicionado());
          break;
        }
        case ITEM_ALTERADO: {
          mergeItemAlterado(other.getItemAlterado());
          break;
        }
        case ITEM_REMOVIDO: {
          mergeItemRemovido(other.getItemRemovido());
          break;
        }
        case CATEGORIAS_ATUALIZADAS: {
          mergeCategoriasAtualizadas(other.getCategoriasAtualizadas());
          break;
        }
        case TIPOEVENTO_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ocorridoEm_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              versaoEvento_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              tipo_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getTransacaoCriadaFieldBuilder().getBuilder(),
                  extensionRegistry);
              tipoEventoCase_ = 4;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getItemAdicionadoFieldBuilder().getBuilder(),
                  extensionRegistry);
              tipoEventoCase_ = 5;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getItemAlteradoFieldBuilder().getBuilder(),
                  extensionRegistry);
              tipoEventoCase_ = 6;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getItemRemovidoFieldBuilder().getBuilder(),
                  extensionRegistry);
              tipoEventoCase_ = 7;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getCategoriasAtualizadasFieldBuilder().getBuilder(),
                  extensionRegistry);
              tipoEventoCase_ = 8;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int tipoEventoCase_ = 0;
    private java.lang.Object tipoEvento_;
    public TipoEventoCase
        getTipoEventoCase() {
      return TipoEventoCase.forNumber(
          tipoEventoCase_);
    }

    public Builder clearTipoEvento() {
      tipoEventoCase_ = 0;
      tipoEvento_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private java.lang.Object ocorridoEm_ = "";
    /**
     * <code>optional string ocorrido_em = 1;</code>
     * @return Whether the ocorridoEm field is set.
     */
    public boolean hasOcorridoEm() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string ocorrido_em = 1;</code>
     * @return The ocorridoEm.
     */
    public java.lang.String getOcorridoEm() {
      java.lang.Object ref = ocorridoEm_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ocorridoEm_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string ocorrido_em = 1;</code>
     * @return The bytes for ocorridoEm.
     */
    public com.google.protobuf.ByteString
        getOcorridoEmBytes() {
      java.lang.Object ref = ocorridoEm_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ocorridoEm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string ocorrido_em = 1;</code>
     * @param value The ocorridoEm to set.
     * @return This builder for chaining.
     */
    public Builder setOcorridoEm(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      ocorridoEm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string ocorrido_em = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOcorridoEm() {
      bitField0_ = (bitField0_ & ~0x00000001);
      ocorridoEm_ = getDefaultInstance().getOcorridoEm();
      onChanged();
      return this;
    }
    /**
     * <code>optional string ocorrido_em = 1;</code>
     * @param value The bytes for ocorridoEm to set.
     * @return This builder for chaining.
     */
    public Builder setOcorridoEmBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      ocorridoEm_ = value;
      onChanged();
      return this;
    }

    private int versaoEvento_ ;
    /**
     * <code>optional int32 versao_evento = 2;</code>
     * @return Whether the versaoEvento field is set.
     */
    @java.lang.Override
    public boolean hasVersaoEvento() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 versao_evento = 2;</code>
     * @return The versaoEvento.
     */
    @java.lang.Override
    public int getVersaoEvento() {
      return versaoEvento_;
    }
    /**
     * <code>optional int32 versao_evento = 2;</code>
     * @param value The versaoEvento to set.
     * @return This builder for chaining.
     */
    public Builder setVersaoEvento(int value) {
      bitField0_ |= 0x00000002;
      versaoEvento_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 versao_evento = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersaoEvento() {
      bitField0_ = (bitField0_ & ~0x00000002);
      versaoEvento_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object tipo_ = "";
    /**
     * <code>optional string tipo = 3;</code>
     * @return Whether the tipo field is set.
     */
    public boolean hasTipo() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string tipo = 3;</code>
     * @return The tipo.
     */
    public java.lang.String getTipo() {
      java.lang.Object ref = tipo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tipo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string tipo = 3;</code>
     * @return The bytes for tipo.
     */
    public com.google.protobuf.ByteString
        getTipoBytes() {
      java.lang.Object ref = tipo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tipo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string tipo = 3;</code>
     * @param value The tipo to set.
     * @return This builder for chaining.
     */
    public Builder setTipo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      tipo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string tipo = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTipo() {
      bitField0_ = (bitField0_ & ~0x00000004);
      tipo_ = getDefaultInstance().getTipo();
      onChanged();
      return this;
    }
    /**
     * <code>optional string tipo = 3;</code>
     * @param value The bytes for tipo to set.
     * @return This builder for chaining.
     */
    public Builder setTipoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000004;
      tipo_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada.Builder, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriadaOrBuilder> transacaoCriadaBuilder_;
    /**
     * <code>.transacao.eventos.TransacaoCriada transacao_criada = 4;</code>
     * @return Whether the transacaoCriada field is set.
     */
    @java.lang.Override
    public boolean hasTransacaoCriada() {
      return tipoEventoCase_ == 4;
    }
    /**
     * <code>.transacao.eventos.TransacaoCriada transacao_criada = 4;</code>
     * @return The transacaoCriada.
     */
    @java.lang.Override
    public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada getTransacaoCriada() {
      if (transacaoCriadaBuilder_ == null) {
        if (tipoEventoCase_ == 4) {
          return (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada) tipoEvento_;
        }
        return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada.getDefaultInstance();
      } else {
        if (tipoEventoCase_ == 4) {
          return transacaoCriadaBuilder_.getMessage();
        }
        return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada.getDefaultInstance();
      }
    }
    /**
     * <code>.transacao.eventos.TransacaoCriada transacao_criada = 4;</code>
     */
    public Builder setTransacaoCriada(br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada value) {
      if (transacaoCriadaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tipoEvento_ = value;
        onChanged();
      } else {
        transacaoCriadaBuilder_.setMessage(value);
      }
      tipoEventoCase_ = 4;
      return this;
    }
    /**
     * <code>.transacao.eventos.TransacaoCriada transacao_criada = 4;</code>
     */
    public Builder setTransacaoCriada(
        br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada.Builder builderForValue) {
      if (transacaoCriadaBuilder_ == null) {
        tipoEvento_ = builderForValue.build();
        onChanged();
      } else {
        transacaoCriadaBuilder_.setMessage(builderForValue.build());
      }
      tipoEventoCase_ = 4;
      return this;
    }
    /**
     * <code>.transacao.eventos.TransacaoCriada transacao_criada = 4;</code>
     */
    public Builder mergeTransacaoCriada(br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada value) {
      if (transacaoCriadaBuilder_ == null) {
        if (tipoEventoCase_ == 4 &&
            tipoEvento_ != br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada.getDefaultInstance()) {
          tipoEvento_ = br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada.newBuilder((br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada) tipoEvento_)
              .mergeFrom(value).buildPartial();
        } else {
          tipoEvento_ = value;
        }
        onChanged();
      } else {
        if (tipoEventoCase_ == 4) {
          transacaoCriadaBuilder_.mergeFrom(value);
        } else {
          transacaoCriadaBuilder_.setMessage(value);
        }
      }
      tipoEventoCase_ = 4;
      return this;
    }
    /**
     * <code>.transacao.eventos.TransacaoCriada transacao_criada = 4;</code>
     */
    public Builder clearTransacaoCriada() {
      if (transacaoCriadaBuilder_ == null) {
        if (tipoEventoCase_ == 4) {
          tipoEventoCase_ = 0;
          tipoEvento_ = null;
          onChanged();
        }
      } else {
        if (tipoEventoCase_ == 4) {
          tipoEventoCase_ = 0;
          tipoEvento_ = null;
        }
        transacaoCriadaBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.transacao.eventos.TransacaoCriada transacao_criada = 4;</code>
     */
    public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada.Builder getTransacaoCriadaBuilder() {
      return getTransacaoCriadaFieldBuilder().getBuilder();
    }
    /**
     * <code>.transacao.eventos.TransacaoCriada transacao_criada = 4;</code>
     */
    @java.lang.Override
    public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriadaOrBuilder getTransacaoCriadaOrBuilder() {
      if ((tipoEventoCase_ == 4) && (transacaoCriadaBuilder_ != null)) {
        return transacaoCriadaBuilder_.getMessageOrBuilder();
      } else {
        if (tipoEventoCase_ == 4) {
          return (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada) tipoEvento_;
        }
        return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada.getDefaultInstance();
      }
    }
    /**
     * <code>.transacao.eventos.TransacaoCriada transacao_criada = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada.Builder, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriadaOrBuilder> 
        getTransacaoCriadaFieldBuilder() {
      if (transacaoCriadaBuilder_ == null) {
        if (!(tipoEventoCase_ == 4)) {
          tipoEvento_ = br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada.getDefaultInstance();
        }
        transacaoCriadaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada.Builder, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriadaOrBuilder>(
                (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.TransacaoCriada) tipoEvento_,
                getParentForChildren(),
                isClean());
        tipoEvento_ = null;
      }
      tipoEventoCase_ = 4;
      onChanged();;
      return transacaoCriadaBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado.Builder, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionadoOrBuilder> itemAdicionadoBuilder_;
    /**
     * <code>.transacao.eventos.ItemAdicionado item_adicionado = 5;</code>
     * @return Whether the itemAdicionado field is set.
     */
    @java.lang.Override
    public boolean hasItemAdicionado() {
      return tipoEventoCase_ == 5;
    }
    /**
     * <code>.transacao.eventos.ItemAdicionado item_adicionado = 5;</code>
     * @return The itemAdicionado.
     */
    @java.lang.Override
    public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado getItemAdicionado() {
      if (itemAdicionadoBuilder_ == null) {
        if (tipoEventoCase_ == 5) {
          return (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado) tipoEvento_;
        }
        return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado.getDefaultInstance();
      } else {
        if (tipoEventoCase_ == 5) {
          return itemAdicionadoBuilder_.getMessage();
        }
        return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado.getDefaultInstance();
      }
    }
    /**
     * <code>.transacao.eventos.ItemAdicionado item_adicionado = 5;</code>
     */
    public Builder setItemAdicionado(br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado value) {
      if (itemAdicionadoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tipoEvento_ = value;
        onChanged();
      } else {
        itemAdicionadoBuilder_.setMessage(value);
      }
      tipoEventoCase_ = 5;
      return this;
    }
    /**
     * <code>.transacao.eventos.ItemAdicionado item_adicionado = 5;</code>
     */
    public Builder setItemAdicionado(
        br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado.Builder builderForValue) {
      if (itemAdicionadoBuilder_ == null) {
        tipoEvento_ = builderForValue.build();
        onChanged();
      } else {
        itemAdicionadoBuilder_.setMessage(builderForValue.build());
      }
      tipoEventoCase_ = 5;
      return this;
    }
    /**
     * <code>.transacao.eventos.ItemAdicionado item_adicionado = 5;</code>
     */
    public Builder mergeItemAdicionado(br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado value) {
      if (itemAdicionadoBuilder_ == null) {
        if (tipoEventoCase_ == 5 &&
            tipoEvento_ != br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado.getDefaultInstance()) {
          tipoEvento_ = br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado.newBuilder((br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado) tipoEvento_)
              .mergeFrom(value).buildPartial();
        } else {
          tipoEvento_ = value;
        }
        onChanged();
      } else {
        if (tipoEventoCase_ == 5) {
          itemAdicionadoBuilder_.mergeFrom(value);
        } else {
          itemAdicionadoBuilder_.setMessage(value);
        }
      }
      tipoEventoCase_ = 5;
      return this;
    }
    /**
     * <code>.transacao.eventos.ItemAdicionado item_adicionado = 5;</code>
     */
    public Builder clearItemAdicionado() {
      if (itemAdicionadoBuilder_ == null) {
        if (tipoEventoCase_ == 5) {
          tipoEventoCase_ = 0;
          tipoEvento_ = null;
          onChanged();
        }
      } else {
        if (tipoEventoCase_ == 5) {
          tipoEventoCase_ = 0;
          tipoEvento_ = null;
        }
        itemAdicionadoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.transacao.eventos.ItemAdicionado item_adicionado = 5;</code>
     */
    public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado.Builder getItemAdicionadoBuilder() {
      return getItemAdicionadoFieldBuilder().getBuilder();
    }
    /**
     * <code>.transacao.eventos.ItemAdicionado item_adicionado = 5;</code>
     */
    @java.lang.Override
    public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionadoOrBuilder getItemAdicionadoOrBuilder() {
      if ((tipoEventoCase_ == 5) && (itemAdicionadoBuilder_ != null)) {
        return itemAdicionadoBuilder_.getMessageOrBuilder();
      } else {
        if (tipoEventoCase_ == 5) {
          return (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado) tipoEvento_;
        }
        return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado.getDefaultInstance();
      }
    }
    /**
     * <code>.transacao.eventos.ItemAdicionado item_adicionado = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado.Builder, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionadoOrBuilder> 
        getItemAdicionadoFieldBuilder() {
      if (itemAdicionadoBuilder_ == null) {
        if (!(tipoEventoCase_ == 5)) {
          tipoEvento_ = br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado.getDefaultInstance();
        }
        itemAdicionadoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado.Builder, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionadoOrBuilder>(
                (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAdicionado) tipoEvento_,
                getParentForChildren(),
                isClean());
        tipoEvento_ = null;
      }
      tipoEventoCase_ = 5;
      onChanged();;
      return itemAdicionadoBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado.Builder, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlteradoOrBuilder> itemAlteradoBuilder_;
    /**
     * <code>.transacao.eventos.ItemAlterado item_alterado = 6;</code>
     * @return Whether the itemAlterado field is set.
     */
    @java.lang.Override
    public boolean hasItemAlterado() {
      return tipoEventoCase_ == 6;
    }
    /**
     * <code>.transacao.eventos.ItemAlterado item_alterado = 6;</code>
     * @return The itemAlterado.
     */
    @java.lang.Override
    public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado getItemAlterado() {
      if (itemAlteradoBuilder_ == null) {
        if (tipoEventoCase_ == 6) {
          return (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado) tipoEvento_;
        }
        return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado.getDefaultInstance();
      } else {
        if (tipoEventoCase_ == 6) {
          return itemAlteradoBuilder_.getMessage();
        }
        return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado.getDefaultInstance();
      }
    }
    /**
     * <code>.transacao.eventos.ItemAlterado item_alterado = 6;</code>
     */
    public Builder setItemAlterado(br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado value) {
      if (itemAlteradoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tipoEvento_ = value;
        onChanged();
      } else {
        itemAlteradoBuilder_.setMessage(value);
      }
      tipoEventoCase_ = 6;
      return this;
    }
    /**
     * <code>.transacao.eventos.ItemAlterado item_alterado = 6;</code>
     */
    public Builder setItemAlterado(
        br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado.Builder builderForValue) {
      if (itemAlteradoBuilder_ == null) {
        tipoEvento_ = builderForValue.build();
        onChanged();
      } else {
        itemAlteradoBuilder_.setMessage(builderForValue.build());
      }
      tipoEventoCase_ = 6;
      return this;
    }
    /**
     * <code>.transacao.eventos.ItemAlterado item_alterado = 6;</code>
     */
    public Builder mergeItemAlterado(br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado value) {
      if (itemAlteradoBuilder_ == null) {
        if (tipoEventoCase_ == 6 &&
            tipoEvento_ != br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado.getDefaultInstance()) {
          tipoEvento_ = br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado.newBuilder((br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado) tipoEvento_)
              .mergeFrom(value).buildPartial();
        } else {
          tipoEvento_ = value;
        }
        onChanged();
      } else {
        if (tipoEventoCase_ == 6) {
          itemAlteradoBuilder_.mergeFrom(value);
        } else {
          itemAlteradoBuilder_.setMessage(value);
        }
      }
      tipoEventoCase_ = 6;
      return this;
    }
    /**
     * <code>.transacao.eventos.ItemAlterado item_alterado = 6;</code>
     */
    public Builder clearItemAlterado() {
      if (itemAlteradoBuilder_ == null) {
        if (tipoEventoCase_ == 6) {
          tipoEventoCase_ = 0;
          tipoEvento_ = null;
          onChanged();
        }
      } else {
        if (tipoEventoCase_ == 6) {
          tipoEventoCase_ = 0;
          tipoEvento_ = null;
        }
        itemAlteradoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.transacao.eventos.ItemAlterado item_alterado = 6;</code>
     */
    public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado.Builder getItemAlteradoBuilder() {
      return getItemAlteradoFieldBuilder().getBuilder();
    }
    /**
     * <code>.transacao.eventos.ItemAlterado item_alterado = 6;</code>
     */
    @java.lang.Override
    public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlteradoOrBuilder getItemAlteradoOrBuilder() {
      if ((tipoEventoCase_ == 6) && (itemAlteradoBuilder_ != null)) {
        return itemAlteradoBuilder_.getMessageOrBuilder();
      } else {
        if (tipoEventoCase_ == 6) {
          return (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado) tipoEvento_;
        }
        return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado.getDefaultInstance();
      }
    }
    /**
     * <code>.transacao.eventos.ItemAlterado item_alterado = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado.Builder, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlteradoOrBuilder> 
        getItemAlteradoFieldBuilder() {
      if (itemAlteradoBuilder_ == null) {
        if (!(tipoEventoCase_ == 6)) {
          tipoEvento_ = br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado.getDefaultInstance();
        }
        itemAlteradoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado.Builder, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlteradoOrBuilder>(
                (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado) tipoEvento_,
                getParentForChildren(),
                isClean());
        tipoEvento_ = null;
      }
      tipoEventoCase_ = 6;
      onChanged();;
      return itemAlteradoBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido.Builder, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovidoOrBuilder> itemRemovidoBuilder_;
    /**
     * <code>.transacao.eventos.ItemRemovido item_removido = 7;</code>
     * @return Whether the itemRemovido field is set.
     */
    @java.lang.Override
    public boolean hasItemRemovido() {
      return tipoEventoCase_ == 7;
    }
    /**
     * <code>.transacao.eventos.ItemRemovido item_removido = 7;</code>
     * @return The itemRemovido.
     */
    @java.lang.Override
    public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido getItemRemovido() {
      if (itemRemovidoBuilder_ == null) {
        if (tipoEventoCase_ == 7) {
          return (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido) tipoEvento_;
        }
        return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido.getDefaultInstance();
      } else {
        if (tipoEventoCase_ == 7) {
          return itemRemovidoBuilder_.getMessage();
        }
        return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido.getDefaultInstance();
      }
    }
    /**
     * <code>.transacao.eventos.ItemRemovido item_removido = 7;</code>
     */
    public Builder setItemRemovido(br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido value) {
      if (itemRemovidoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tipoEvento_ = value;
        onChanged();
      } else {
        itemRemovidoBuilder_.setMessage(value);
      }
      tipoEventoCase_ = 7;
      return this;
    }
    /**
     * <code>.transacao.eventos.ItemRemovido item_removido = 7;</code>
     */
    public Builder setItemRemovido(
        br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido.Builder builderForValue) {
      if (itemRemovidoBuilder_ == null) {
        tipoEvento_ = builderForValue.build();
        onChanged();
      } else {
        itemRemovidoBuilder_.setMessage(builderForValue.build());
      }
      tipoEventoCase_ = 7;
      return this;
    }
    /**
     * <code>.transacao.eventos.ItemRemovido item_removido = 7;</code>
     */
    public Builder mergeItemRemovido(br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido value) {
      if (itemRemovidoBuilder_ == null) {
        if (tipoEventoCase_ == 7 &&
            tipoEvento_ != br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido.getDefaultInstance()) {
          tipoEvento_ = br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido.newBuilder((br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido) tipoEvento_)
              .mergeFrom(value).buildPartial();
        } else {
          tipoEvento_ = value;
        }
        onChanged();
      } else {
        if (tipoEventoCase_ == 7) {
          itemRemovidoBuilder_.mergeFrom(value);
        } else {
          itemRemovidoBuilder_.setMessage(value);
        }
      }
      tipoEventoCase_ = 7;
      return this;
    }
    /**
     * <code>.transacao.eventos.ItemRemovido item_removido = 7;</code>
     */
    public Builder clearItemRemovido() {
      if (itemRemovidoBuilder_ == null) {
        if (tipoEventoCase_ == 7) {
          tipoEventoCase_ = 0;
          tipoEvento_ = null;
          onChanged();
        }
      } else {
        if (tipoEventoCase_ == 7) {
          tipoEventoCase_ = 0;
          tipoEvento_ = null;
        }
        itemRemovidoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.transacao.eventos.ItemRemovido item_removido = 7;</code>
     */
    public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido.Builder getItemRemovidoBuilder() {
      return getItemRemovidoFieldBuilder().getBuilder();
    }
    /**
     * <code>.transacao.eventos.ItemRemovido item_removido = 7;</code>
     */
    @java.lang.Override
    public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovidoOrBuilder getItemRemovidoOrBuilder() {
      if ((tipoEventoCase_ == 7) && (itemRemovidoBuilder_ != null)) {
        return itemRemovidoBuilder_.getMessageOrBuilder();
      } else {
        if (tipoEventoCase_ == 7) {
          return (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido) tipoEvento_;
        }
        return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido.getDefaultInstance();
      }
    }
    /**
     * <code>.transacao.eventos.ItemRemovido item_removido = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido.Builder, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovidoOrBuilder> 
        getItemRemovidoFieldBuilder() {
      if (itemRemovidoBuilder_ == null) {
        if (!(tipoEventoCase_ == 7)) {
          tipoEvento_ = br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido.getDefaultInstance();
        }
        itemRemovidoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido.Builder, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovidoOrBuilder>(
                (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemRemovido) tipoEvento_,
                getParentForChildren(),
                isClean());
        tipoEvento_ = null;
      }
      tipoEventoCase_ = 7;
      onChanged();;
      return itemRemovidoBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas.Builder, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadasOrBuilder> categoriasAtualizadasBuilder_;
    /**
     * <code>.transacao.eventos.CategoriasAtualizadas categorias_atualizadas = 8;</code>
     * @return Whether the categoriasAtualizadas field is set.
     */
    @java.lang.Override
    public boolean hasCategoriasAtualizadas() {
      return tipoEventoCase_ == 8;
    }
    /**
     * <code>.transacao.eventos.CategoriasAtualizadas categorias_atualizadas = 8;</code>
     * @return The categoriasAtualizadas.
     */
    @java.lang.Override
    public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas getCategoriasAtualizadas() {
      if (categoriasAtualizadasBuilder_ == null) {
        if (tipoEventoCase_ == 8) {
          return (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas) tipoEvento_;
        }
        return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas.getDefaultInstance();
      } else {
        if (tipoEventoCase_ == 8) {
          return categoriasAtualizadasBuilder_.getMessage();
        }
        return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas.getDefaultInstance();
      }
    }
    /**
     * <code>.transacao.eventos.CategoriasAtualizadas categorias_atualizadas = 8;</code>
     */
    public Builder setCategoriasAtualizadas(br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas value) {
      if (categoriasAtualizadasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tipoEvento_ = value;
        onChanged();
      } else {
        categoriasAtualizadasBuilder_.setMessage(value);
      }
      tipoEventoCase_ = 8;
      return this;
    }
    /**
     * <code>.transacao.eventos.CategoriasAtualizadas categorias_atualizadas = 8;</code>
     */
    public Builder setCategoriasAtualizadas(
        br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas.Builder builderForValue) {
      if (categoriasAtualizadasBuilder_ == null) {
        tipoEvento_ = builderForValue.build();
        onChanged();
      } else {
        categoriasAtualizadasBuilder_.setMessage(builderForValue.build());
      }
      tipoEventoCase_ = 8;
      return this;
    }
    /**
     * <code>.transacao.eventos.CategoriasAtualizadas categorias_atualizadas = 8;</code>
     */
    public Builder mergeCategoriasAtualizadas(br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas value) {
      if (categoriasAtualizadasBuilder_ == null) {
        if (tipoEventoCase_ == 8 &&
            tipoEvento_ != br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas.getDefaultInstance()) {
          tipoEvento_ = br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas.newBuilder((br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas) tipoEvento_)
              .mergeFrom(value).buildPartial();
        } else {
          tipoEvento_ = value;
        }
        onChanged();
      } else {
        if (tipoEventoCase_ == 8) {
          categoriasAtualizadasBuilder_.mergeFrom(value);
        } else {
          categoriasAtualizadasBuilder_.setMessage(value);
        }
      }
      tipoEventoCase_ = 8;
      return this;
    }
    /**
     * <code>.transacao.eventos.CategoriasAtualizadas categorias_atualizadas = 8;</code>
     */
    public Builder clearCategoriasAtualizadas() {
      if (categoriasAtualizadasBuilder_ == null) {
        if (tipoEventoCase_ == 8) {
          tipoEventoCase_ = 0;
          tipoEvento_ = null;
          onChanged();
        }
      } else {
        if (tipoEventoCase_ == 8) {
          tipoEventoCase_ = 0;
          tipoEvento_ = null;
        }
        categoriasAtualizadasBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.transacao.eventos.CategoriasAtualizadas categorias_atualizadas = 8;</code>
     */
    public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas.Builder getCategoriasAtualizadasBuilder() {
      return getCategoriasAtualizadasFieldBuilder().getBuilder();
    }
    /**
     * <code>.transacao.eventos.CategoriasAtualizadas categorias_atualizadas = 8;</code>
     */
    @java.lang.Override
    public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadasOrBuilder getCategoriasAtualizadasOrBuilder() {
      if ((tipoEventoCase_ == 8) && (categoriasAtualizadasBuilder_ != null)) {
        return categoriasAtualizadasBuilder_.getMessageOrBuilder();
      } else {
        if (tipoEventoCase_ == 8) {
          return (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas) tipoEvento_;
        }
        return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas.getDefaultInstance();
      }
    }
    /**
     * <code>.transacao.eventos.CategoriasAtualizadas categorias_atualizadas = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas.Builder, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadasOrBuilder> 
        getCategoriasAtualizadasFieldBuilder() {
      if (categoriasAtualizadasBuilder_ == null) {
        if (!(tipoEventoCase_ == 8)) {
          tipoEvento_ = br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas.getDefaultInstance();
        }
        categoriasAtualizadasBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas.Builder, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadasOrBuilder>(
                (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.CategoriasAtualizadas) tipoEvento_,
                getParentForChildren(),
                isClean());
        tipoEvento_ = null;
      }
      tipoEventoCase_ = 8;
      onChanged();;
      return categoriasAtualizadasBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:transacao.eventos.EventoTransacao)
  }

  // @@protoc_insertion_point(class_scope:transacao.eventos.EventoTransacao)
  private static final br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao();
  }

  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EventoTransacao>
      PARSER = new com.google.protobuf.AbstractParser<EventoTransacao>() {
    @java.lang.Override
    public EventoTransacao parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EventoTransacao> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EventoTransacao> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventoTransacao getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

