// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/eventos_transacao.proto

package br.com.pine.gerenciador.modelo.dominio.transacao.eventos;

public interface ItemAlteradoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transacao.eventos.ItemAlterado)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string descricao_original = 1;</code>
   * @return Whether the descricaoOriginal field is set.
   */
  boolean hasDescricaoOriginal();
  /**
   * <code>optional string descricao_original = 1;</code>
   * @return The descricaoOriginal.
   */
  java.lang.String getDescricaoOriginal();
  /**
   * <code>optional string descricao_original = 1;</code>
   * @return The bytes for descricaoOriginal.
   */
  com.google.protobuf.ByteString
      getDescricaoOriginalBytes();

  /**
   * <code>optional string descricao_nova = 2;</code>
   * @return Whether the descricaoNova field is set.
   */
  boolean hasDescricaoNova();
  /**
   * <code>optional string descricao_nova = 2;</code>
   * @return The descricaoNova.
   */
  java.lang.String getDescricaoNova();
  /**
   * <code>optional string descricao_nova = 2;</code>
   * @return The bytes for descricaoNova.
   */
  com.google.protobuf.ByteString
      getDescricaoNovaBytes();

  /**
   * <code>optional .transacao.eventos.ObjetosDeValor.ValorItem valor_item_novo = 3;</code>
   * @return Whether the valorItemNovo field is set.
   */
  boolean hasValorItemNovo();
  /**
   * <code>optional .transacao.eventos.ObjetosDeValor.ValorItem valor_item_novo = 3;</code>
   * @return The valorItemNovo.
   */
  br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItem getValorItemNovo();
  /**
   * <code>optional .transacao.eventos.ObjetosDeValor.ValorItem valor_item_novo = 3;</code>
   */
  br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItemOrBuilder getValorItemNovoOrBuilder();

  /**
   * <code>repeated string categorias = 4;</code>
   * @return A list containing the categorias.
   */
  java.util.List<java.lang.String>
      getCategoriasList();
  /**
   * <code>repeated string categorias = 4;</code>
   * @return The count of categorias.
   */
  int getCategoriasCount();
  /**
   * <code>repeated string categorias = 4;</code>
   * @param index The index of the element to return.
   * @return The categorias at the given index.
   */
  java.lang.String getCategorias(int index);
  /**
   * <code>repeated string categorias = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the categorias at the given index.
   */
  com.google.protobuf.ByteString
      getCategoriasBytes(int index);
}
