// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventos_transacao.proto

package br.com.pine.gerenciador.modelo.dominio.transacao.eventos;

public interface ItemAdicionadoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transacao.eventos.ItemAdicionado)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string descricao = 1;</code>
   * @return Whether the descricao field is set.
   */
  boolean hasDescricao();
  /**
   * <code>optional string descricao = 1;</code>
   * @return The descricao.
   */
  java.lang.String getDescricao();
  /**
   * <code>optional string descricao = 1;</code>
   * @return The bytes for descricao.
   */
  com.google.protobuf.ByteString
      getDescricaoBytes();

  /**
   * <code>optional .transacao.eventos.ObjetosDeValor.ValorItem valor_item = 2;</code>
   * @return Whether the valorItem field is set.
   */
  boolean hasValorItem();
  /**
   * <code>optional .transacao.eventos.ObjetosDeValor.ValorItem valor_item = 2;</code>
   * @return The valorItem.
   */
  br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItem getValorItem();
  /**
   * <code>optional .transacao.eventos.ObjetosDeValor.ValorItem valor_item = 2;</code>
   */
  br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItemOrBuilder getValorItemOrBuilder();

  /**
   * <code>repeated string categorias = 3;</code>
   * @return A list containing the categorias.
   */
  java.util.List<java.lang.String>
      getCategoriasList();
  /**
   * <code>repeated string categorias = 3;</code>
   * @return The count of categorias.
   */
  int getCategoriasCount();
  /**
   * <code>repeated string categorias = 3;</code>
   * @param index The index of the element to return.
   * @return The categorias at the given index.
   */
  java.lang.String getCategorias(int index);
  /**
   * <code>repeated string categorias = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the categorias at the given index.
   */
  com.google.protobuf.ByteString
      getCategoriasBytes(int index);
}
