// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventos_transacao.proto

package br.com.pine.gerenciador.modelo.dominio.transacao.eventos;

public interface ItemRemovidoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transacao.eventos.ItemRemovido)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string descricao = 1;</code>
   * @return Whether the descricao field is set.
   */
  boolean hasDescricao();
  /**
   * <code>optional string descricao = 1;</code>
   * @return The descricao.
   */
  java.lang.String getDescricao();
  /**
   * <code>optional string descricao = 1;</code>
   * @return The bytes for descricao.
   */
  com.google.protobuf.ByteString
      getDescricaoBytes();
}
