// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventos_transacao.proto

package br.com.pine.gerenciador.modelo.dominio.transacao.eventos;

import br.com.pine.gerenciador.modelo.dominio.Evento;

/**
 * Protobuf type {@code transacao.eventos.ItemAlterado}
 */
public final class ItemAlterado extends
    com.google.protobuf.GeneratedMessageV3 implements Evento,
    // @@protoc_insertion_point(message_implements:transacao.eventos.ItemAlterado)
    ItemAlteradoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ItemAlterado.newBuilder() to construct.
  private ItemAlterado(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ItemAlterado() {
    descricaoOriginal_ = "";
    descricaoNova_ = "";
    categorias_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ItemAlterado();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventosTransacao.internal_static_transacao_eventos_ItemAlterado_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventosTransacao.internal_static_transacao_eventos_ItemAlterado_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado.class, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado.Builder.class);
  }

  private int bitField0_;
  public static final int DESCRICAO_ORIGINAL_FIELD_NUMBER = 1;
  private volatile java.lang.Object descricaoOriginal_;
  /**
   * <code>optional string descricao_original = 1;</code>
   * @return Whether the descricaoOriginal field is set.
   */
  @java.lang.Override
  public boolean hasDescricaoOriginal() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string descricao_original = 1;</code>
   * @return The descricaoOriginal.
   */
  @java.lang.Override
  public java.lang.String getDescricaoOriginal() {
    java.lang.Object ref = descricaoOriginal_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      descricaoOriginal_ = s;
      return s;
    }
  }
  /**
   * <code>optional string descricao_original = 1;</code>
   * @return The bytes for descricaoOriginal.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescricaoOriginalBytes() {
    java.lang.Object ref = descricaoOriginal_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      descricaoOriginal_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRICAO_NOVA_FIELD_NUMBER = 2;
  private volatile java.lang.Object descricaoNova_;
  /**
   * <code>optional string descricao_nova = 2;</code>
   * @return Whether the descricaoNova field is set.
   */
  @java.lang.Override
  public boolean hasDescricaoNova() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string descricao_nova = 2;</code>
   * @return The descricaoNova.
   */
  @java.lang.Override
  public java.lang.String getDescricaoNova() {
    java.lang.Object ref = descricaoNova_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      descricaoNova_ = s;
      return s;
    }
  }
  /**
   * <code>optional string descricao_nova = 2;</code>
   * @return The bytes for descricaoNova.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescricaoNovaBytes() {
    java.lang.Object ref = descricaoNova_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      descricaoNova_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALOR_ITEM_NOVO_FIELD_NUMBER = 3;
  private br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItem valorItemNovo_;
  /**
   * <code>optional .transacao.eventos.ObjetosDeValor.ValorItem valor_item_novo = 3;</code>
   * @return Whether the valorItemNovo field is set.
   */
  @java.lang.Override
  public boolean hasValorItemNovo() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .transacao.eventos.ObjetosDeValor.ValorItem valor_item_novo = 3;</code>
   * @return The valorItemNovo.
   */
  @java.lang.Override
  public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItem getValorItemNovo() {
    return valorItemNovo_ == null ? br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItem.getDefaultInstance() : valorItemNovo_;
  }
  /**
   * <code>optional .transacao.eventos.ObjetosDeValor.ValorItem valor_item_novo = 3;</code>
   */
  @java.lang.Override
  public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItemOrBuilder getValorItemNovoOrBuilder() {
    return valorItemNovo_ == null ? br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItem.getDefaultInstance() : valorItemNovo_;
  }

  public static final int CATEGORIAS_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList categorias_;
  /**
   * <code>repeated string categorias = 4;</code>
   * @return A list containing the categorias.
   */
  public com.google.protobuf.ProtocolStringList
      getCategoriasList() {
    return categorias_;
  }
  /**
   * <code>repeated string categorias = 4;</code>
   * @return The count of categorias.
   */
  public int getCategoriasCount() {
    return categorias_.size();
  }
  /**
   * <code>repeated string categorias = 4;</code>
   * @param index The index of the element to return.
   * @return The categorias at the given index.
   */
  public java.lang.String getCategorias(int index) {
    return categorias_.get(index);
  }
  /**
   * <code>repeated string categorias = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the categorias at the given index.
   */
  public com.google.protobuf.ByteString
      getCategoriasBytes(int index) {
    return categorias_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, descricaoOriginal_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, descricaoNova_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getValorItemNovo());
    }
    for (int i = 0; i < categorias_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, categorias_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, descricaoOriginal_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, descricaoNova_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getValorItemNovo());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < categorias_.size(); i++) {
        dataSize += computeStringSizeNoTag(categorias_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCategoriasList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado)) {
      return super.equals(obj);
    }
    br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado other = (br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado) obj;

    if (hasDescricaoOriginal() != other.hasDescricaoOriginal()) return false;
    if (hasDescricaoOriginal()) {
      if (!getDescricaoOriginal()
          .equals(other.getDescricaoOriginal())) return false;
    }
    if (hasDescricaoNova() != other.hasDescricaoNova()) return false;
    if (hasDescricaoNova()) {
      if (!getDescricaoNova()
          .equals(other.getDescricaoNova())) return false;
    }
    if (hasValorItemNovo() != other.hasValorItemNovo()) return false;
    if (hasValorItemNovo()) {
      if (!getValorItemNovo()
          .equals(other.getValorItemNovo())) return false;
    }
    if (!getCategoriasList()
        .equals(other.getCategoriasList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDescricaoOriginal()) {
      hash = (37 * hash) + DESCRICAO_ORIGINAL_FIELD_NUMBER;
      hash = (53 * hash) + getDescricaoOriginal().hashCode();
    }
    if (hasDescricaoNova()) {
      hash = (37 * hash) + DESCRICAO_NOVA_FIELD_NUMBER;
      hash = (53 * hash) + getDescricaoNova().hashCode();
    }
    if (hasValorItemNovo()) {
      hash = (37 * hash) + VALOR_ITEM_NOVO_FIELD_NUMBER;
      hash = (53 * hash) + getValorItemNovo().hashCode();
    }
    if (getCategoriasCount() > 0) {
      hash = (37 * hash) + CATEGORIAS_FIELD_NUMBER;
      hash = (53 * hash) + getCategoriasList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code transacao.eventos.ItemAlterado}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:transacao.eventos.ItemAlterado)
      br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlteradoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventosTransacao.internal_static_transacao_eventos_ItemAlterado_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventosTransacao.internal_static_transacao_eventos_ItemAlterado_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado.class, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado.Builder.class);
    }

    // Construct using br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getValorItemNovoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      descricaoOriginal_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      descricaoNova_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      if (valorItemNovoBuilder_ == null) {
        valorItemNovo_ = null;
      } else {
        valorItemNovoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      categorias_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.EventosTransacao.internal_static_transacao_eventos_ItemAlterado_descriptor;
    }

    @java.lang.Override
    public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado getDefaultInstanceForType() {
      return br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado.getDefaultInstance();
    }

    @java.lang.Override
    public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado build() {
      br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado buildPartial() {
      br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado result = new br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.descricaoOriginal_ = descricaoOriginal_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.descricaoNova_ = descricaoNova_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        if (valorItemNovoBuilder_ == null) {
          result.valorItemNovo_ = valorItemNovo_;
        } else {
          result.valorItemNovo_ = valorItemNovoBuilder_.build();
        }
        to_bitField0_ |= 0x00000004;
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        categorias_ = categorias_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.categorias_ = categorias_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado) {
        return mergeFrom((br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado other) {
      if (other == br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado.getDefaultInstance()) return this;
      if (other.hasDescricaoOriginal()) {
        bitField0_ |= 0x00000001;
        descricaoOriginal_ = other.descricaoOriginal_;
        onChanged();
      }
      if (other.hasDescricaoNova()) {
        bitField0_ |= 0x00000002;
        descricaoNova_ = other.descricaoNova_;
        onChanged();
      }
      if (other.hasValorItemNovo()) {
        mergeValorItemNovo(other.getValorItemNovo());
      }
      if (!other.categorias_.isEmpty()) {
        if (categorias_.isEmpty()) {
          categorias_ = other.categorias_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureCategoriasIsMutable();
          categorias_.addAll(other.categorias_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              descricaoOriginal_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              descricaoNova_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getValorItemNovoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureCategoriasIsMutable();
              categorias_.add(s);
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object descricaoOriginal_ = "";
    /**
     * <code>optional string descricao_original = 1;</code>
     * @return Whether the descricaoOriginal field is set.
     */
    public boolean hasDescricaoOriginal() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string descricao_original = 1;</code>
     * @return The descricaoOriginal.
     */
    public java.lang.String getDescricaoOriginal() {
      java.lang.Object ref = descricaoOriginal_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        descricaoOriginal_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string descricao_original = 1;</code>
     * @return The bytes for descricaoOriginal.
     */
    public com.google.protobuf.ByteString
        getDescricaoOriginalBytes() {
      java.lang.Object ref = descricaoOriginal_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        descricaoOriginal_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string descricao_original = 1;</code>
     * @param value The descricaoOriginal to set.
     * @return This builder for chaining.
     */
    public Builder setDescricaoOriginal(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      descricaoOriginal_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string descricao_original = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescricaoOriginal() {
      bitField0_ = (bitField0_ & ~0x00000001);
      descricaoOriginal_ = getDefaultInstance().getDescricaoOriginal();
      onChanged();
      return this;
    }
    /**
     * <code>optional string descricao_original = 1;</code>
     * @param value The bytes for descricaoOriginal to set.
     * @return This builder for chaining.
     */
    public Builder setDescricaoOriginalBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      descricaoOriginal_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object descricaoNova_ = "";
    /**
     * <code>optional string descricao_nova = 2;</code>
     * @return Whether the descricaoNova field is set.
     */
    public boolean hasDescricaoNova() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string descricao_nova = 2;</code>
     * @return The descricaoNova.
     */
    public java.lang.String getDescricaoNova() {
      java.lang.Object ref = descricaoNova_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        descricaoNova_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string descricao_nova = 2;</code>
     * @return The bytes for descricaoNova.
     */
    public com.google.protobuf.ByteString
        getDescricaoNovaBytes() {
      java.lang.Object ref = descricaoNova_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        descricaoNova_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string descricao_nova = 2;</code>
     * @param value The descricaoNova to set.
     * @return This builder for chaining.
     */
    public Builder setDescricaoNova(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      descricaoNova_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string descricao_nova = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescricaoNova() {
      bitField0_ = (bitField0_ & ~0x00000002);
      descricaoNova_ = getDefaultInstance().getDescricaoNova();
      onChanged();
      return this;
    }
    /**
     * <code>optional string descricao_nova = 2;</code>
     * @param value The bytes for descricaoNova to set.
     * @return This builder for chaining.
     */
    public Builder setDescricaoNovaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      descricaoNova_ = value;
      onChanged();
      return this;
    }

    private br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItem valorItemNovo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItem, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItem.Builder, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItemOrBuilder> valorItemNovoBuilder_;
    /**
     * <code>optional .transacao.eventos.ObjetosDeValor.ValorItem valor_item_novo = 3;</code>
     * @return Whether the valorItemNovo field is set.
     */
    public boolean hasValorItemNovo() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .transacao.eventos.ObjetosDeValor.ValorItem valor_item_novo = 3;</code>
     * @return The valorItemNovo.
     */
    public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItem getValorItemNovo() {
      if (valorItemNovoBuilder_ == null) {
        return valorItemNovo_ == null ? br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItem.getDefaultInstance() : valorItemNovo_;
      } else {
        return valorItemNovoBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .transacao.eventos.ObjetosDeValor.ValorItem valor_item_novo = 3;</code>
     */
    public Builder setValorItemNovo(br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItem value) {
      if (valorItemNovoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        valorItemNovo_ = value;
        onChanged();
      } else {
        valorItemNovoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .transacao.eventos.ObjetosDeValor.ValorItem valor_item_novo = 3;</code>
     */
    public Builder setValorItemNovo(
        br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItem.Builder builderForValue) {
      if (valorItemNovoBuilder_ == null) {
        valorItemNovo_ = builderForValue.build();
        onChanged();
      } else {
        valorItemNovoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .transacao.eventos.ObjetosDeValor.ValorItem valor_item_novo = 3;</code>
     */
    public Builder mergeValorItemNovo(br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItem value) {
      if (valorItemNovoBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
            valorItemNovo_ != null &&
            valorItemNovo_ != br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItem.getDefaultInstance()) {
          valorItemNovo_ =
            br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItem.newBuilder(valorItemNovo_).mergeFrom(value).buildPartial();
        } else {
          valorItemNovo_ = value;
        }
        onChanged();
      } else {
        valorItemNovoBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .transacao.eventos.ObjetosDeValor.ValorItem valor_item_novo = 3;</code>
     */
    public Builder clearValorItemNovo() {
      if (valorItemNovoBuilder_ == null) {
        valorItemNovo_ = null;
        onChanged();
      } else {
        valorItemNovoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <code>optional .transacao.eventos.ObjetosDeValor.ValorItem valor_item_novo = 3;</code>
     */
    public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItem.Builder getValorItemNovoBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getValorItemNovoFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .transacao.eventos.ObjetosDeValor.ValorItem valor_item_novo = 3;</code>
     */
    public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItemOrBuilder getValorItemNovoOrBuilder() {
      if (valorItemNovoBuilder_ != null) {
        return valorItemNovoBuilder_.getMessageOrBuilder();
      } else {
        return valorItemNovo_ == null ?
            br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItem.getDefaultInstance() : valorItemNovo_;
      }
    }
    /**
     * <code>optional .transacao.eventos.ObjetosDeValor.ValorItem valor_item_novo = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItem, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItem.Builder, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItemOrBuilder> 
        getValorItemNovoFieldBuilder() {
      if (valorItemNovoBuilder_ == null) {
        valorItemNovoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItem, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItem.Builder, br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ObjetosDeValor.ValorItemOrBuilder>(
                getValorItemNovo(),
                getParentForChildren(),
                isClean());
        valorItemNovo_ = null;
      }
      return valorItemNovoBuilder_;
    }

    private com.google.protobuf.LazyStringList categorias_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureCategoriasIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        categorias_ = new com.google.protobuf.LazyStringArrayList(categorias_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <code>repeated string categorias = 4;</code>
     * @return A list containing the categorias.
     */
    public com.google.protobuf.ProtocolStringList
        getCategoriasList() {
      return categorias_.getUnmodifiableView();
    }
    /**
     * <code>repeated string categorias = 4;</code>
     * @return The count of categorias.
     */
    public int getCategoriasCount() {
      return categorias_.size();
    }
    /**
     * <code>repeated string categorias = 4;</code>
     * @param index The index of the element to return.
     * @return The categorias at the given index.
     */
    public java.lang.String getCategorias(int index) {
      return categorias_.get(index);
    }
    /**
     * <code>repeated string categorias = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the categorias at the given index.
     */
    public com.google.protobuf.ByteString
        getCategoriasBytes(int index) {
      return categorias_.getByteString(index);
    }
    /**
     * <code>repeated string categorias = 4;</code>
     * @param index The index to set the value at.
     * @param value The categorias to set.
     * @return This builder for chaining.
     */
    public Builder setCategorias(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCategoriasIsMutable();
      categorias_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string categorias = 4;</code>
     * @param value The categorias to add.
     * @return This builder for chaining.
     */
    public Builder addCategorias(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCategoriasIsMutable();
      categorias_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string categorias = 4;</code>
     * @param values The categorias to add.
     * @return This builder for chaining.
     */
    public Builder addAllCategorias(
        java.lang.Iterable<java.lang.String> values) {
      ensureCategoriasIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, categorias_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string categorias = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCategorias() {
      categorias_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string categorias = 4;</code>
     * @param value The bytes of the categorias to add.
     * @return This builder for chaining.
     */
    public Builder addCategoriasBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureCategoriasIsMutable();
      categorias_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:transacao.eventos.ItemAlterado)
  }

  // @@protoc_insertion_point(class_scope:transacao.eventos.ItemAlterado)
  private static final br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado();
  }

  public static br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ItemAlterado>
      PARSER = new com.google.protobuf.AbstractParser<ItemAlterado>() {
    @java.lang.Override
    public ItemAlterado parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ItemAlterado> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ItemAlterado> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.com.pine.gerenciador.modelo.dominio.transacao.eventos.ItemAlterado getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

