// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventos_transacao.proto

package br.com.pine.gerenciador.modelo.dominio.transacao.eventos;

public interface ObjetosDeValorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transacao.eventos.ObjetosDeValor)
    com.google.protobuf.MessageOrBuilder {
}
